winget install Microsoft.WindowsTerminal
winget install 7zip.7zip
winget install Git.Git
winget install JanDeDobbeleer.OhMyPosh
winget install Microsoft.DotNet.SDK.5
winget install Microsoft.DotNet.SDK.6
winget install Microsoft.PowerToys
winget install Microsoft.VisualStudioCode
winget install Notepad++.Notepad++
winget install SlackTechnologies.Slack
winget install Microsoft.VisualStudio.2022.Professional
winget install Mozilla.Firefox
winget install JetBrains.DataGrip
winget install 9PGCV4V3BK4W